---
npm_packages:
  - ajv-cli
  - bats
  - eslint
  - eslint-config-airbnb
  - eslint-plugin-import
  - eslint-plugin-toml
  - jsonlint
  - markdownlint
  # - npx
  - prettier
  - puppeteer
  - serverless
  - typescript
  - wscat
  # - yarn
