---
npm_packages:
  - ajv-cli
  # - bats
  # - eslint
  # - eslint-config-airbnb
  # - eslint-plugin-import
  # - eslint-plugin-toml
  # - htmlhint
  # - jsonlint
  # - markdownlint-cli2
  # - prettier
  - puppeteer
  - serverless
  # - typescript
  - wscat
  # - @anthropic-ai/claude-code
  # - @github/copilot
  # - @google/gemini-cli
  # - @openai/codex
