---
galaxy_info:
  author: dceoy
  description: Python development environment setup
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: MacOSX
      versions:
        - all
  galaxy_tags:
    - python
    - development
    - programming

dependencies: []

allow_duplicates: false
