---
brew_packages:
  with_options:
    - name: cairo
      options:
        - with-x11
    - name: imagemagick
      options:
        - with-fontconfig
        - with-librsvg
  without_options:
    - atk
    - ansible
    - aria2
    - autoconf
    - automake
    - aws-cdk
    - awscli
    - bazel
    # - bats-core
    # - bcftools
    # - bedtools
    - binutils
    - boost
    # - bwa
    - cabal-install
    - circleci
    - cloudflared
    - cloudformation-guard
    - colordiff
    # - conjure-up
    - coreutils
    - corkscrew
    - cosign
    - curl
    # - cyberduck
    - diffutils
    - dvc
    - ed
    - elixir
    - fcrackzip
    - fd
    - ffmpeg
    - findutils
    - freetds
    - freetype
    - fribidi
    - gawk
    - gcc
    - gdal
    - gdbm
    - gflags
    - gh
    - ghc
    - git
    - glog
    - gnu-indent
    - gnu-sed
    - gnu-tar
    - gnu-which
    - gnutls
    - go
    - goodwithtech/r/dockle
    - gopls
    - goreleaser
    - gpg
    - groff
    - grep
    - gzip
    - hadolint
    - harfbuzz
    - hdf5
    - htop
    - hugo
    - hunspell
    # - igv
    - imagemagick
    - jq
    - jsonlint
    - kubectl
    - leveldb
    - libgit2
    - libjpeg
    - librsvg
    - libssh2
    - libtiff
    - libxml2
    - little-cms2
    - llvm
    - lmdb
    - lua
    - luajit
    # - md5sha1sum
    - mercurial
    - ncdu
    - nkf
    - nmap
    - node
    - npm
    - ollama
    - open-mpi
    - opencv
    - openjdk
    - openssl
    - p7zip
    - pandoc
    - parallel
    - pbzip2
    - pdf2svg
    # - picard-tools
    - pigz
    - pipx
    - pkg-config
    - postgresql
    - protobuf
    - python
    - quicktype
    - rain
    - readline
    - redis
    - rename
    - rsync
    - ruby
    - rust
    - rustup
    # - samtools
    - sbt
    - scala
    - screen
    - shellcheck
    - shunit2
    - snappy
    - sqlite
    - supervisor
    # - szip
    - tcl-tk
    - terragrunt
    - tfenv
    - tflint
    - tfsec
    - tig
    - tldr
    - tmux
    - tree
    - trivy
    - v8
    - vim
    - wakeonlan
    - watch
    - wdiff
    - webp
    - wget
    - zip
    - zlib
    - zsh
brew_cask_packages:
  - adobe-acrobat-reader
  # - authy
  # - amazon-music
  # - chatgpt
  # - chrome-remote-desktop-host
  # - cursor
  # - discord
  - docker
  - drawio
  # - dropbox
  # - endnote
  # - figma
  # - firefox
  # - gimp
  # - google-drive
  - google-chrome
  # - google-cloud-sdk
  - google-japanese-ime
  # - handbrake
  - iterm2
  # - microsoft-edge
  - microsoft-office
  # - microsoft-remote-desktop
  - miro
  # - opera
  - r
  # - rstudio
  # - session-manager-plugin
  - slack
  # - tailscale
  - visual-studio-code
  # - vnc-viewer
  # - wine-stable
  - xquartz
  # - zoom
