---
brew_packages:
  with_options:
    - name: cairo
      options:
        - with-x11
    - name: imagemagick
      options:
        - with-fontconfig
        - with-librsvg
  without_options:
    - act
    - ansible
    - ansible-lint
    - aria2
    # - autoconf
    # - automake
    - aws-cdk
    - awscli
    # - bazel
    - bats-core
    # - bcftools
    # - bedtools
    - binutils
    # - boost
    # - cabal-install
    # - circleci
    - cloudflared
    - cloudformation-guard
    - colordiff
    - copilot-cli
    - coreutils
    - corkscrew
    - cosign
    - csvkit
    - curl
    # - cyberduck
    - diffutils
    - dvc
    # - ed
    # - elixir
    - eslint
    - fcrackzip
    - fd
    - ffmpeg
    - findutils
    # - freetds
    # - freetype
    # - fribidi
    - gawk
    - gemini-cli
    - gcc
    # - gdal
    # - gdbm
    # - gflags
    - gh
    # - ghc
    - git
    # - glog
    # - gnu-indent
    - gnu-sed
    - gnu-tar
    - gnu-which
    # - gnutls
    - go
    - gopls
    # - goreleaser
    # - gpg
    - groff
    - grep
    - grip
    - gzip
    - hadolint
    # - harfbuzz
    - hdf5
    - htmlhint
    - htop
    - hugo
    - hunspell
    # - igv
    - imagemagick
    - jq
    - jsonlint
    # - kubectl
    # - leveldb
    # - libgit2
    # - libjpeg
    # - librsvg
    # - libssh2
    # - libtiff
    # - libxml2
    # - little-cms2
    - llm
    # - llvm
    # - lmdb
    - lua
    - luajit
    - markdownlint-cli2
    - md5sha1sum
    - mercurial
    - ncdu
    - nkf
    - nmap
    - node
    - npm
    - ollama
    # - openjdk
    # - openssl
    - p7zip
    - pandoc
    # - parallel
    - pbzip2
    - pdf2svg
    # - picard-tools
    - pigz
    - pinact
    # - pipx
    # - pkg-config
    # - postgresql
    - prettier
    # - protobuf
    - pyright
    - python
    - quicktype
    - r
    - rain
    # - readline
    # - redis
    - rename
    - rsync
    - ruby
    - ruff
    # - rust
    # - rustup
    # - samtools
    # - screen
    - shellcheck
    - shunit2
    # - snappy
    - sqlite
    - stylelint
    # - supervisor
    # - tailscale
    # - tcl-tk
    - tenv
    - tflint
    - tig
    - tmux
    - tree
    - trivy
    - typescript
    - uv
    # - v8
    - vim
    - vulture
    - wakeonlan
    - watch
    - wdiff
    # - webp
    - wget
    - yamllint
    - yq
    - zip
    - zizmor
    # - zlib
    - zsh
brew_cask_packages:
  - adobe-acrobat-reader
  # - amazon-music
  # - chatgpt
  # - chatgpt-atlas
  # - chrome-remote-desktop-host
  # - claude
  - claude-code
  - codex
  # - cursor
  # - dbeaver-community
  # - discord
  - docker
  - drawio
  # - dropbox
  # - endnote
  # - figma
  # - firefox
  # - gimp
  # - google-drive
  - google-chrome
  - google-cloud-sdk
  - google-japanese-ime
  # - handbrake
  - iterm2
  # - lm-studio
  - microsoft-office
  - miro
  # - notion
  # - opera
  # - rstudio
  - slack
  - visual-studio-code
  # - vnc-viewer
  # - wine-stable
  - xquartz
  # - zoom
