---
- name: Notify updates of the external devices via Slack
  when:
    - slack_token is defined
    - slack_channel is defined
    - slack_icon_url is defined
  delegate_to: localhost
  community.general.slack:
    msg: 'The external devices were updated.'
    token: "{{ slack_token }}"
    channel: "#{{ slack_channel }}"
    username: "{{ ansible_user }}@{{ inventory_hostname }}"
    icon_url: "{{ slack_icon_url }}"
