---
pip_packages:
  3:
    - git+https://github.com/dceoy/oanda-cli.git
    - alpha_vantage
    - ansible-lint
    - apache-airflow
    - apache-libcloud
    - aws-cdk-lib
    - aws-lambda-powertools
    - bash_kernel
    - bcolz
    - biopython
    - beautifulsoup4
    - black
    - bokeh
    - boto3
    - bottle
    - bayesian-optimization
    - catboost
    - cfn-lint
    - colored-traceback
    - coloredlogs
    - cookiecutter
    - csvkit
    - cutadapt
    - cython
    - docker
    - docopt
    - fabric
    - fastapi
    - fbprophet
    - feather-format
    - floyd-cli
    - ggplot
    - git-remote-codecommit
    - greenlet
    - grip
    - h5py
    - hiredis
    - holoviews
    - hyperopt
    - injector
    - interpret
    - ipykernel
    - ipython
    - jsonschema
    - jupyter
    - jupyter_contrib_nbextensions
    - jupyterthemes
    - keras
    - langchain
    - lifelines
    - lightgbm
    - llama-cpp-python
    - llama-index
    - luigi
    - magika
    - matplotlib
    - mkl
    - mock
    - MonkeyType
    - mypy
    - nose
    - notebook
    - notedown
    - numexpr
    - numpy
    - pandas
    - pandas-datareader
    - pandera
    - pillow
    - pip
    - pipx
    - plotly
    - poetry
    - polars
    - pr-agent
    - pre-commit
    - psutil
    - psycopg2-binary
    - pubnub
    - plyvel
    - pydantic
    - pydot
    - pygam
    - pyinstaller
    - pymc
    - pynvim
    - pyopenssl
    - pypandoc
    - pypdf2
    - pyper
    - pyright
    - pysam
    - pystan
    - pytest
    - pytoml
    - pytorch
    - pyyaml
    - redis
    - requests
    - requests_oauthlib
    - rpy2
    - ruff
    - sabr
    - scikit-learn
    - scipy
    - scss
    - seaborn
    - selenium
    - setuptools
    - six
    - sklearn-pandas
    - sktime
    - sphinx
    - sqlmodel
    - statsmodels
    - streamlit
    - streamz
    - sympy
    - tensorflow
    - testfixtures
    - tflearn
    - torch
    - torchvision
    - tornado
    - tox
    - tqdm
    - tryceratops
    - twine
    - twitter
    - types-docopt
    - types-jsonschema
    - types-setuptools
    - umap-learn
    - vim-vint
    - vulture
    - webtest
    - xgboost
    - xmltodict
    - yamllint
    - yq
